/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AnyMatch: typeof import('./src/components/form-control/AnyMatch.vue')['default']
    CompleteMatch: typeof import('./src/components/form-control/CompleteMatch.vue')['default']
    DisplayRowNumber: typeof import('./src/components/form-control/DisplayRowNumber.vue')['default']
    DynamicInput: typeof import('./src/components/form-control/DynamicInput.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    FuzzyMatch: typeof import('./src/components/form-control/FuzzyMatch.vue')['default']
    KeywordPosition: typeof import('./src/components/form-control/KeywordPosition.vue')['default']
    LimitTime: typeof import('./src/components/form-control/LimitTime.vue')['default']
    NoMatch: typeof import('./src/components/form-control/NoMatch.vue')['default']
    SearchEngineList: typeof import('./src/components/SearchEngineList.vue')['default']
    SearchInput: typeof import('./src/components/SearchInput.vue')['default']
    SearchLanguage: typeof import('./src/components/form-control/SearchLanguage.vue')['default']
    SiteFormat: typeof import('./src/components/form-control/SiteFormat.vue')['default']
    SiteSearch: typeof import('./src/components/form-control/SiteSearch.vue')['default']
  }
}
